### ISSUE TITLE
NodeTypeMappingBuilderInterface does not exist

### ISSUE THREAD

**Issue by johannessteu** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer#36]
This commits https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer/commit/464e2ab4583fde067e8cc7555fb678b33d0466f1 adds the NodeTypeMappingBuilderInterface to an upcoming 5.0 release for CR-Adaptor. But it is already released in 3.1.0 wich is compativle to CR-Adaptor 4.0 and the Interface does not exist there. So this breaks with

```
The object "Flowpack\ElasticSearch\ContentRepositoryAdaptor\Driver\NodeTypeMappingBuilderInterface" which was specified as a property in the object configuration of object "Flowpack\ElasticSearch\ContentRepositoryQueueIndexer\Command\NodeIndexQueueCommandController" (automatically registered class) does not exist.
```

**Comment by peterbucher** [comment]
@johannessteu Same problem here. "composer update" leaded to break the code because of this mistake. You know if i can manually work around this, until the error is fixed?

**Comment by peterbucher** [comment]
To workaround i did the following:

Change
`"flowpack/elasticsearch-contentrepositoryadaptor": "^4.0",`

To
`"flowpack/elasticsearch-contentrepositoryadaptor": "4.0.*",`

In the composer.json
